### ISSUE TITLE
Multiple subjects for bibliography and book profiles

### ISSUE THREAD

**Issue by informaticmonad** [zepheira/bibframe-scribe#12]
Multiple subjects can be added to the vinyl record, electronic and print dissertation, and image profiles. 

However in the electronic and print bibliography and book profiles, the subject pull-down dims after the first subject is added.

**Comment by zepheiryan** [comment]
Yes, the profiles are configured to demonstrate capabilities, such as as multiple vs. single values.  We may arrange to update demo profiles to reflect more realistic usage over time, but for now they're in a state to make the point more than to be accurate (not that we can't eventually have both, of course).
